---

### USER ROLES DEFINITION
### Create a new role by adding another hash with a unique name of the role as well as a list of rights. Unassignable states that the role cannot be assigned to users.
### Available rights are: 'admin', 'view'
user_roles:
  -
    name: ADMIN
    rights:
      - admin
  -
    name: GUEST
    rights:
      - view
    unassignable: true
  -
    name: API_KEY
    rights:
      - admin
    unassignable: true

# Flags for using external authentication source
external_auth: true
