### API KEY USED FOR API-CALLS
api_key_users:
  -
    username: test_key_user
    name: Test key User
    role: API_KEY
    api_key: test_key
# External authentication source
external_auth_url: "https://login-server.example.org/auth"

store_path: "tmp/test_store"

cache_path: "/home/xcarji/dliver-cache"
solr_url: "http://localhost:8983/solr/dliver"
thumbnail_file_group: "web"
default_thumbnail: "spec/fixtures/default_thumbnail.jpg"
file_access_group: "bilder"
