### API KEY USED FOR API-CALLS
api_key_users:
  -
    username: test_key_user
    name: Test key User
    role: API_KEY
    api_key: test_key
# External authentication source
external_auth_url: "https://login-server.example.org/auth"

store_path: "spec/fixtures/test-packages"

solr_url: "http://localhost:8983/solr/dliver"
